### PR TITLE
netd: Allow devices to opt-out of the tethering active FTP helper

### PR DESCRIPTION
**Pull request by voidz777**
Without this commit, the angler or bullhead wifihotspot will not work.
If there is no problem, please add this commit.

### CODE REVIEW

**Comment by fgl27** [comment]
https://review.lineageos.org/c/LineageOS/android_system_netd/+/234190

**Comment by voidz777** [comment]
Thank you for confirming.
I know it's an abandon. 
But there is little progress in developing angler and bullhead los 16, so there is only one solution. :(
aosip has this commit added by the maintainer of bullhead.
https://review.aosiprom.com/c/AOSIP/platform_system_netd/+/7455

**Comment by fgl27** [comment]
but what about the "Backport exists" I assume is a already set workaround base on a boardconfig flag or a kernel change.
Have you search for it or ask there on los review to know what is the "Backport exists"?

**Comment by voidz777** [comment]
OK. I'm stupid I can't do kernel backport, so I'll wait until someone solves the problem. :'(
Thank you very much.

**Comment by fgl27** [comment]
ask there is probably a simple commit that you can just pick.

**Comment by voidz777** [comment]
I have a look at the commit of kernel_samsung_msm8974 of klte maintainer Kevin Haggerty who addressed this issue around Nov 28, 2018.
Thank you. Have a nice weekend :)

**Comment by fgl27** [comment]
you welcome, if that doesn't work let us know.

**Pull request closed without merging**
